name: Update Homebrew TAP
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      sleep:
        description: 'Seconds to sleep before proceed'
        required: true
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Wait for pypi to update mirrors"
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        sleep ${{ github.event.inputs.sleep }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r gen_resources/requirements.txt
    - name: Generate formula
      run: |
        python gen_resources/generate_formula_version.py
    - name: Autocommit new release
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        branch: master
        commit_options: '--no-verify --signoff'
        file_pattern: Formula/*.rb digest.txt
        repository: .
